-- Create translation table for Bike content
create table if not exists bike_translations (
  id bigint generated by default as identity primary key,
  bike_id bigint references bikes(id) on delete cascade not null,
  language text not null,
  bike_desc text,
  meta_desc text,
  overall_score_explanation text,
  performance_score_explanation text,
  value_score_explanation text,
  fit_score_explanation text,
  general_score_explanation text,
  climbing_efficiency_explanation text,
  aerodynamics_explanation text,
  riding_position_explanation text,
  handling_explanation text,
  fit_flexibility_explanation text,
  ride_comfort_explanation text,
  build_quality_explanation text,
  value_for_money_explanation text,
  surface_range_explanation text,
  speed_reason text,
  battery_reason text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(bike_id, language)
);

-- Enable RLS
alter table bike_translations enable row level security;

-- Policy for reading (public)
create policy "Public translations are viewable by everyone." on bike_translations
  for select using (true);

-- Policy for authenticated users (admins) to modify
create policy "Authenticated users can modify translations" on bike_translations
  for all using (auth.role() = 'authenticated');
